Artifact: "test_stats.json"
TimingArtifact: "test_timing.csv"
Algorithms:
  GCN:
    key: gnn
    regular: b44af85cabc544c5a65c61e479a15946
    temporal: c22b776933fe403a8fe98d35a0818b25
    color: "xkcd:turquoise"
    marker: "d"
  GCNII:
    key: gnn
    regular: fb29c05a0fc9457c85c50825bab46b23
    temporal: c9e41e257e184ce1903136970c959753
    color: "xkcd:magenta"
    marker: "*"
  GIN:
    key: gnn
    regular: cf346426cced4250a2c35522bb0bd948
    temporal: 5e1d69b3eb72487696136c002cba3529
    color: "xkcd:grass green"
    marker: "P"
  GraphSage:
    key: gnn
    regular: 529ac3687e8e408e857520b374eabb04
    temporal: 0e6de54681c44e71b6719b8e909e6959
    color: "xkcd:dark blue"
    marker: "X"
Plots:
  ROC:
    marker_size: 60
    font_size: 12
  Bounds:
    font_size: 12
    line_width: 2
  Detection:
    marker_size: 60
    font_size: 12
    dataset: test.pkl
    inference: test_inference.csv
    last_only: True